services:
  giftbot:
    build: .
    platform: linux/amd64
    env_file:
      - .env
    environment:
      DATABASE_PATH: /app/data/giftbot.sqlite
    volumes:
      - giftbot_data2:/app/data
    restart: unless-stopped

volumes:
  giftbot_data2:
